Update SCP to Version 0.14.1
AnacondaRecipes/scp-feedstock pull request #3
Opened 2021-10-26 22:25 UTC by varlackc

scp 0.14.1

1. check the upstream
https://github.com/jbardin/scp.py/tree/v0.14.1

2. check the pinnings
https://github.com/jbardin/scp.py/blob/v0.14.1/setup.py
https://github.com/jbardin/scp.py/blob/v0.14.1/setup.cfg

3. check changelogs
https://github.com/jbardin/scp.py/blob/v0.14.1/CHANGELOG.md

The changes mentioned were mainly new features
- Don't fail if `pathlib` doesn't import (Python 2)
- Accept `unicode` objects as paths (Python 2)
- Accept iterables other than list and tuple in `get()` and `put()`
- Accept `pathlib.Path` objects

4. additional research
https://github.com/conda-forge/scp-feedstock/issues

There are currently no open issues mentioned in conda forge at the time of the review

5. verify dev_url
dev_url: https://github.com/jbardin/scp.py

6. verify doc_url
The doc_url seems to be a duplicate of the dev_url, 
in order to correct that issues research was done by looking in pypi.org and on readthedocs

https://pypi.org/project/scp/

However no external documentation page seems to exist for scp. 
It seems more logical on that case to point out to the ReadMe file in the package instead of just pointing to the exact same location that the dev_url is pointing. 
In the mean time we should keep an eye out for new official documentation been release somewhere else. 

doc_url: https://github.com/jbardin/scp.py/blob/master/README.rst

7. verify that pip is in the test section
8. verify the test section
9. additional tests

In order to test the `scp` package version `0.14.1` the following command was used:
`conda build scp-feedstock --test` 
The test result was the following:
`All tests passed`

since there are no packages depending on `scp` an import test is not possible, however 
we will try to install the package from source to see if there are any installation issues. 

the following command was used to install the local file
`conda install scp-0.14.1-pyhd3eb1b0_0.tar.bz2 `

The result was as follows

`Downloading and Extracting Packages
##################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done`

Now to conduct the local import test the following steps were taken:
use python in interactive mode `python -i`
import the package using the following command `import scp`

The package was imported without any errors. 

Based on the research findings and on the test results we can conclude that it is safe to update `scp` to version `0.14.1`

2021-10-27 05:33 UTC, katietz requested changes

2021-10-27 05:33 UTC, katietz commented on recipe/meta.yaml
> +  skip: True  # [py<3.7]
please use here '[py<37]'. Don't use floating-point notation

2021-10-27 14:19 UTC, varlackc commented on recipe/meta.yaml
>    script: {{ PYTHON }} -m pip install . --no-deps -vv
The skip section was updated:
The notation for the python pinning was modified, in addition s390x was added to the skip since there seem to be dependency issues in s390x and SCP is not in the list of packages for IBM

2021-10-27 14:23 UTC, varlackc commented on recipe/meta.yaml
> +  skip: True  # [py<3.7]
The requested changes were made, in addition s390x was added to the skip, and a comment was added
https://github.com/AnacondaRecipes/scp-feedstock/blob/update_to_0.14.1/recipe/meta.yaml#L15

2021-10-27 16:09 UTC, skupr-anaconda approved these changes

2021-10-28 12:22 UTC, katietz approved these changes
Thanks

2021-10-29 20:29 UTC, merged